version: '3'
services:
  nginx-web:
    image: nginx:1.12-alpine
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../conf.d:/etc/nginx/conf.d
      - ../vhost.d:/etc/nginx/vhost.d
      - ../html:/usr/share/nginx/html
      - ../certs:/etc/nginx/certs:ro
      - ../htpasswd:/etc/nginx/htpasswd:ro
    logging:
      options:
        max-size: "4m"
        max-file: "10"

  nginx-gen:
    image: jwilder/docker-gen:0.8.1
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - ../conf.d:/etc/nginx/conf.d
      - ../vhost.d:/etc/nginx/vhost.d
      - ../html:/usr/share/nginx/html
      - ../certs:/etc/nginx/certs:ro
      - ../htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      options:
        max-size: "2m"
        max-file: "10"
networks:
  default:
    external:
      name: nginx-proxy
