services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.8-alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro



volumes:
  certs:
  html:

networks:
    default:
        name: nginx-proxy
        external: true
